### ISSUE TITLE
PSN user is not authenticated

### ISSUE THREAD

**Issue by hyam0615** [Lacro59/playnite-successstory-plugin#344]
Im sure it's already authenticated but still get this error

**Comment by Efraim2704** [comment]
same for me

**Comment by eskypi** [comment]
same for me :(

**Comment by ceccarelli** [comment]
Same problem here, Playnite 10.9 and SuccessStory 3.1

**Comment by damirarh** [comment]
I'm having the same problem as well, with latest version of Playnite (10.9) and SuccessStory (3.1).

I did some debugging and the code correctly detects that the user is logged in but then fails to get the mobile token because the request to `mobileCodeUrl` fails with a `400 BadRequest`. Did a Sony API change?

**Comment by ScrewThisNoise** [comment]
Same issue 
o/

**Comment by eskypi** [comment]
any solution?

**Comment by hyam0615** [comment]
is psn trophies abandoned?

**Comment by eskypi** [comment]
> is psn trophies abandoned?

Yes

**Comment by Lacro59** [comment]
fixed
