### ISSUE TITLE
Steam achievements do not load properly

### ISSUE THREAD

**Issue by GaetanCia** [Lacro59/playnite-successstory-plugin#446]
Achievements are not synchronizing properly on Steam games
My steam profile is public.

playnite-successstory-plugin version : 3.1.7
![playnite_version](https://github.com/Lacro59/playnite-successstory-plugin/assets/35254377/7459553f-fb6d-408f-b31f-ccc96ba9a4de)

extension.log:
11-01 14:23:20.288|INFO |SuccessStory#SteamAchievements:SteamApi.GetAchievements()
11-01 14:23:22.448|INFO |SuccessStory#PluginDatabaseObject`4:0/78 achievements find for The Witcher 3: Wild Hunt - 9295b9c3-4d5c-4bb5-970a-c4fba2ec3274

![success](https://github.com/Lacro59/playnite-successstory-plugin/assets/35254377/cf21c417-e11f-4a93-bf43-c81a467318e5)

**Comment by Driesmann** [comment]
Same issue.

**Comment by alnviana** [comment]
I have the same problem.
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/31132223/f48ceb19-c7e9-4dad-8ba2-ce5f4fa06e7a)

As explained on [this comment](https://github.com/Lacro59/playnite-successstory-plugin/issues/444#issuecomment-1881580442), using API key solves the problem.

Before:
```
29-01 01:06:08.373|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for Portal - 78c79976-746d-4804-994d-8bfdc45a7306
29-01 01:06:08.373|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: False, SteamIsPrivate: False
29-01 01:06:10.366|INFO |SuccessStory#SteamAchievements:SteamApi.GetAchievements()
29-01 01:06:14.698|WARN |SuccessStory#TrueAchievements:No url for GetEstimateTimeToUnlock()
29-01 01:06:14.698|INFO |SuccessStory#PluginDatabaseObject`4:0/15 achievements find for Portal - 78c79976-746d-4804-994d-8bfdc45a7306
29-01 01:06:14.721|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for Portal 2 - 7c032e65-2523-453c-9572-67c402c1356b
29-01 01:06:14.721|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: False, SteamIsPrivate: False
29-01 01:06:15.280|INFO |SuccessStory#SteamAchievements:SteamApi.GetAchievements()
29-01 01:06:17.549|WARN |SuccessStory#TrueAchievements:No url for GetEstimateTimeToUnlock()
29-01 01:06:17.549|INFO |SuccessStory#PluginDatabaseObject`4:0/51 achievements find for Portal 2 - 7c032e65-2523-453c-9572-67c402c1356b
29-01 01:06:17.549|INFO |SuccessStory#PluginDatabaseObject`4:Task GetSelectData() - 00:09.52 for 2/2 items
```

After:
```
29-01 01:27:03.249|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for Portal - 78c79976-746d-4804-994d-8bfdc45a7306
29-01 01:27:03.249|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: True, SteamIsPrivate: False
29-01 01:27:04.003|INFO |SuccessStory#SteamAchievements:SteamApi.GetAchievements()
29-01 01:27:06.198|WARN |SuccessStory#TrueAchievements:No url for GetEstimateTimeToUnlock()
29-01 01:27:06.198|INFO |SuccessStory#PluginDatabaseObject`4:15/15 achievements find for Portal - 78c79976-746d-4804-994d-8bfdc45a7306
29-01 01:27:06.223|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for Portal 2 - 7c032e65-2523-453c-9572-67c402c1356b
29-01 01:27:06.223|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: True, SteamIsPrivate: False
29-01 01:27:06.684|INFO |SuccessStory#SteamAchievements:SteamApi.GetAchievements()
29-01 01:27:09.534|WARN |SuccessStory#TrueAchievements:No url for GetEstimateTimeToUnlock()
29-01 01:27:09.534|INFO |SuccessStory#PluginDatabaseObject`4:4/51 achievements find for Portal 2 - 7c032e65-2523-453c-9572-67c402c1356b
29-01 01:27:09.534|INFO |SuccessStory#PluginDatabaseObject`4:Task GetSelectData() - 00:06.36 for 2/2 items
```

**Comment by Lacro59** [comment]
This is a test version for Steam achievements.
Can you test if you have a problem with Steam?
Be careful if you post a log file because it is a debug version with potential personal information.
[playnite-successstory-plugin_3_1_7_dev.zip](https://github.com/user-attachments/files/15986439/playnite-successstory-plugin_3_1_7_dev.zip)

**Comment by alnviana** [comment]
Sure. :)
Just to be clear, I'm using Success Story 3.1.7.

As I already have everything synchronized, I did these steps:
1. Removed Steam API Key from Success Story settings.
2. Closed Playnite.
3. Removed Portal achievement file Json from Success Story ExtensionsData folder.
4. Opened Playnite.
5. Tried to sync Portal achievements. Result: Didn't sync anything, 0/15.
6. Installed the plugin that you send.
7. Tried to sync Portal again, but I received a notification saying like "Success Story is misconfigured".
8. In Success Story Steam settings, now there is some new options, I just input Account Name and ID.
9. Tried again to sync Portal achievements. Result: Synced, 15/15.

I tried with just Steam API Key as before, without putting Account Name and ID on step 8, but this didn't work.
At least we receive a notification saying that there is some setting wrong. Better than that would be if the notification say something like "You need to input Steam Account Name and ID".

I send everything because I don't know if this is the planned behavior.
