### ISSUE TITLE
RetroAchievements not hashing and misreporting

### ISSUE THREAD

**Issue by nxllxvxid** [Lacro59/playnite-successstory-plugin#459]
I am currently trying to import the achievements for Daxter on the PSP [which has achievements as you can see here](https://retroachievements.org/game/10477), when looking in the logs this is what it tells me:

```
18-02 11:14:58.428|WARN |SuccessStory#RetroAchievements:Hash impossible - The file is too long - D:\Emulators\PSP\ROMs\\(2006) Daxter.iso
18-02 11:14:58.428|WARN |SuccessStory#RetroAchievements:No game find for Daxter with Sony PlayStation Portable in 10
```

This also applies to almost every game which refuses to import from RetroAchievements

**Comment by UrbanCMC** [comment]
What worked for me was editing the RA platform associations in the SuccessStory settings and making sure the platform the game belongs to is only assigned to one RA platform. Otherwise it seems to only search for the game in the first platform it matches with. In your case the "in 10" in your log is the "32X" platform.

It should look something like this:
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/9725089/58808186-f84c-4b4a-a5b1-7ddb120eec58)

**Comment by nxllxvxid** [comment]
That's the thing I already have it setup like that:
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/19805594/8aaa4d52-63bd-461f-9189-5ed7da345d16)

**Comment by UrbanCMC** [comment]
Did you also make sure that "Sony PlayStation Portable" is *only* assigned to that platform? From your log I would expect that it is also assigned to "32X".

**Comment by nxllxvxid** [comment]
it is but it should still function like it previously did, going through all options and removing it is absurd

**Comment by nxllxvxid** [comment]
> Did you also make sure that "Sony PlayStation Portable" is _only_ assigned to that platform? From your log I would expect that it is also assigned to "32X".

This does work but for previous use of the extension this shouldn't be necessary
