### ISSUE TITLE
Playnite crashes on system startup when "Launch Playnite when you start your computer" is enabled

### ISSUE THREAD

**Issue by woutercools** [Lacro59/playnite-successstory-plugin#483]
Playnite crashes on system startup when "Launch Playnite when you start your computer" is enabled.

Exiting Playnite and launching it manually, does not crash Playnite.

[SuccessStory_crashatstartup.zip](https://github.com/user-attachments/files/16085719/SuccessStory_crashatstartup.zip)

**Comment by xCeeTee** [comment]
I believe you've posted this to the wrong place, as it doesn't seem like your issue lies with SuccessStory at all. I cannot find anything in your main log concerning SS. There is an error that keeps on occuring that the Indie Gala library extension has failed. And another one with your Xbox extension. The problem you're having seems to be either;

1. Indie Gala extension is broken. Verify by uninstalling it. Close Playnite with alt+q and then reopen it again. If everything loads up properly then it shouldn't trigger the crash. I'd imagine that IG could have the issue because you're not signed in, but the extension could also be bugging out after a Playnite update. 

2. Xbox account needs verifying. Unfortunately, you have to do this from time to time. However, I highly doubt that's the issue.

I also think that it's confirmation bias on your part with the "launch Playnite when..." is the cause. When you have Playnite open for the first time it goes through a list of processes. Checks your library, looks for extension updates, looks for achievement updates via SS, looks for missing metadata and the list continues for a long time. When it's checking your library, I think the Indie Gala extension is what's causing the crash.

Just want to say I'm not the dev of SuccessStory but I've been fixing issues in Playnite for a couple of years now. If you still have the issue then let me know. Take this post down too, it's intended for the main Playnite github page whereas this issue thread is for SuccessStory, the achievement manager extension.

**Comment by woutercools** [comment]
> I believe you've posted this to the wrong place, as it doesn't seem like your issue lies with SuccessStory at all. I cannot find anything in your main log concerning SS. There is an error that keeps on occuring that the Indie Gala library extension has failed. And another one with your Xbox extension. The problem you're having seems to be either;

Sorry about that. It thought it was Successtory bugging out because it throws the error.

> 1. Indie Gala extension is broken. Verify by uninstalling it. Close Playnite with alt+q and then reopen it again. If everything loads up properly then it shouldn't trigger the crash. I'd imagine that IG could have the issue because you're not signed in, but the extension could also be bugging out after a Playnite update.

I'll reference this post in the Indiegala Github page.

> 2. Xbox account needs verifying. Unfortunately, you have to do this from time to time. However, I highly doubt that's the issue.

True, rectified that.

> Just want to say I'm not the dev of SuccessStory but I've been fixing issues in Playnite for a couple of years now. If you still have the issue then let me know. Take this post down too, it's intended for the main Playnite github page whereas this issue thread is for SuccessStory, the achievement manager extension.

I posted this report in the main Playnite Github page before, but I was told to post it in the Successtory plugin Github instead.
