### ISSUE TITLE
Constantly recurring database updates with v3.3

### ISSUE THREAD

**Issue by robbely** [Lacro59/playnite-successstory-plugin#517]
**Describe the bug**
Whenever I start playnite with this update, I have a dialog "Downloading data from installed games" which occurs each time. Also when I change selected game I have a dialog "Database migration" which occurs each time.

**To Reproduce**
Open playniite with addon v3.3 installed. Change selected game.

**Expected behavior**
The first dialog makes sense, but I would expect it to only occur once, when starting for the first time after updating to 3.3
The second dialog I would have expected to not be there as migrations should have taken place during the first dialog.

**Screenshots**
N/A

**Extensions log**
N/A - I have uninstalled the addon for now as the updates and issues ares taking up too much time for me.

**Comment by ccrowles** [comment]
Same issue here, unfortunately.
Every time that I start Playnite, if the option "download" is turned on, instead of downloading data of newly installed games SuccessStory re-downloads the data of _all_ installed games (which in my case are a lot, so this makes Playnite unusable for me for five minutes...).

It says "SuccessStory: Downloading data from new games", but none of the games are new, and the data gets redownloaded at every Playnite startup.

Screenshot:
![image](https://github.com/user-attachments/assets/e32aa2cd-58f2-4a30-a88d-1609c7069666)

Logs:
[playnite.log](https://github.com/user-attachments/files/16825429/playnite.log)
[extensions.log](https://github.com/user-attachments/files/16825430/extensions.log)

**Comment by veksha** [comment]
same. also Epic achievements dont work with 3.3

**Comment by ccrowles** [comment]
The issue still occurs for me on SuccessStory 3.3.1 (I updated it today, so I assume it should have been the fixed version?).

**Comment by CrashSpyro** [comment]
![20240902_082919](https://github.com/user-attachments/assets/a2e7cb85-136c-4005-a569-e6cd0d6e48f5)
There's a way to prevent that, just uncheck Automatically Import data like the picture above

**Comment by ccrowles** [comment]
I hope the dev reopens this issue thread because the problem, as showed by multiple people, has not been fixed unfortunately.
